"""initial_tables

Revision ID: c11f0ad4c81e
Revises: 
Create Date: 2026-03-18 02:29:44.357264
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'c11f0ad4c81e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lenders',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('product_type', sa.String(length=50), nullable=True),
    sa.Column('min_fico', sa.Integer(), nullable=True),
    sa.Column('min_dscr', sa.Float(), nullable=True),
    sa.Column('max_ltv', sa.Float(), nullable=True),
    sa.Column('max_ltc', sa.Float(), nullable=True),
    sa.Column('min_loan', sa.Float(), nullable=True),
    sa.Column('max_loan', sa.Float(), nullable=True),
    sa.Column('geography', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('persons',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.String(length=10), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('company', sa.String(length=255), nullable=True),
    sa.Column('esp_tags', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('deals',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('person_id', sa.String(length=36), nullable=False),
    sa.Column('product_lane', sa.String(length=20), nullable=False),
    sa.Column('lead_type', sa.String(length=10), nullable=False),
    sa.Column('channel', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('property_address', sa.Text(), nullable=True),
    sa.Column('property_city', sa.String(length=100), nullable=True),
    sa.Column('property_state', sa.String(length=2), nullable=True),
    sa.Column('property_zip', sa.String(length=10), nullable=True),
    sa.Column('property_type', sa.String(length=50), nullable=True),
    sa.Column('units', sa.Integer(), nullable=True),
    sa.Column('financials', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ai_triage_result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('deal_score', sa.String(length=10), nullable=True),
    sa.Column('monday_item_id', sa.String(length=50), nullable=True),
    sa.Column('salesforce_opp_id', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('monday_item_id'),
    sa.UniqueConstraint('salesforce_opp_id')
    )
    op.create_index('ix_deals_person_id', 'deals', ['person_id'], unique=False)
    op.create_index('ix_deals_product_lane', 'deals', ['product_lane'], unique=False)
    op.create_index('ix_deals_status', 'deals', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_deals_status', table_name='deals')
    op.drop_index('ix_deals_product_lane', table_name='deals')
    op.drop_index('ix_deals_person_id', table_name='deals')
    op.drop_table('deals')
    op.drop_table('persons')
    op.drop_table('lenders')
    # ### end Alembic commands ###
